server:
  error:
    include-message: always
  port: 8080
  servlet:
    context-path: /api
spring:
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  datasource:
    url: jdbc:postgresql://${PGHOST_MAIN}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
logging:
  level:
    org:
      hibernate:
        nodeValue: INFO
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
